Beginner-level/DSA/Area of rectangle.txt
=> Program for area of rectangle

Intermediate-Level/DSA/Infix to Postfix.txt
=> Update Infix to Postfix.txt

Intermediate-Level/DSA/Stack operations.txt
=> Update Stack operations.txt

Beginner-level/DSA/Check-whether-number-is-even-or-not.txt
=> Program for checking if a number is even or not

Beginner-level/DSA/Cubeofnumber.txt
=> Program of finding cube of a number

Beginner-level/DSA/Add_Two_Matrices.py
=> Add two_Matrices using python

Beginner-level/DSA/Check vowel or consonant.txt
=> Program to check vowels or consonants

Beginner-level/DSA/Print your name.txt
Name - Vishal Arunagiri .
Community - GDSC-RAIT , RAIT ACM .
=> Program for Print Your Name

Beginner-level/DSA/Area of triangle.txt
=> Area-of-triangle

Beginner-level/DSA/Hollow Diamond.txt
=> Hollow Diamond

Beginner-level/DSA/Print odd numbers.txt
=> Printing Odd numbers in C

Beginner-level/DSA/Print even numbers.txt
=> Even numbers in C

Intermediate-Level/DSA/Factorial of Number.txt
=> factorial-CPP

Beginner-level/DSA/Area of rectangle.txt
=> Programme for Area of rectangle

Beginner-level/DSA/Geometric Progression.txt
=> GP using C

Beginner-level/DSA/Square of number.txt, Beginner-level/DSA/square of number.txt
=> Program for Square of Number 2

Beginner-level/DSA/Area of square.txt
=> Program Area of square

Beginner-level/DSA/Palindrome pattern1.txt
=> Palindrome Pattern

Beginner-level/DSA/Half Pyramid.txt
=> Program for printing Half Pyramid

Beginner-level/DSA/Convert lower case to uppercase.txt
=> Convert Lower Case to Upper Case in Java

Beginner-level/DSA/convert uppercase to lowercase.txt
=> Convert Upper Case to Lower Case

Beginner-level/DSA/Inverted Full Pyramid.txt
=> Inverted Full Pyramid

Beginner-level/DSA/Area of square.txt
=> Program for Area of a Square

Intermediate-Level/DSA/3 * 3 matrix multiplication.txt
=> 3*3 matrix multiplication

Beginner-level/DSA/Pascal's Triangle.txt
=> Pascal's Triangle

Beginner-level/DSA/Check-whether-number-is-even-or-not.txt
=> Program to Check Whether the given Number is Even or Not

Beginner-level/DSA/Check Palindrome.txt
=> Program Check Palindrome

Beginner-level/DSA/Cubeofnumber.txt
=> cube of number

Beginner-level/DSA/Check whether number is prime or not.txt
=> Program to Check Whether Given Number is Prime or Not

Beginner-level/DSA/CheckArmstrong.txt
=> Program to check armstrong

Beginner-level/DSA/count number of space in sentence.txt
=> count the number of spaces in the sentence

Beginner-level/DSA/Check-whether-number-is-even-or-not.txt
=> check even or not

Beginner-level/DSA/Print random number.txt
=> Program to Print Random Numbers

Beginner-level/DSA/Reverse Digits.txt
=> Program for Reverse Digits

Beginner-level/DSA/convert uppercase to lowercase.txt
=> Uppercase-to-lowercase

Beginner-level/DSA/count number of space in sentence.txt
=> Program to count spaces in a sentence

Beginner-level/DSA/Print your name.txt
=> Program For Printing Name

Beginner-level/DSA/Area of square.txt
=> Program for area of square

Beginner-level/DSA/Check Palindrome.txt
=> Check Palindrome Number using Java

Beginner-level/DSA/Cubeofnumber.txt
=> Cube-of-a-number

Beginner-level/DSA/Convert lower case to uppercase.txt
=> lowercase-to-uppercase

Beginner-level/DSA/Check whether number is prime or not.txt
=> Program for checking prime number using java

Beginner-level/DSA/Check whether number is prime or not.txt, Beginner-level/DSA/Fibonacci.txt
=> Fibonacci series

Beginner-level/DSA/Check whether number is prime or not.txt, Beginner-level/DSA/square of number.txt
=> Square of numbers using java

Beginner-level/DSA/Check vowel or consonant.txt
=> Vowel-or-consonant

Beginner-level/DSA/Check whether number is prime or not.txt, Beginner-level/DSA/Diplay prime factors.txt
=> Prime factors

Intermediate-Level/DSA/3 * 3 matrix multiplication.txt
=> 3 * 3 matrix multiplication

Beginner-level/DSA/Print random number.txt
=> Program to print random number using Java

Beginner-level/DSA/Hollow inverted half pyramid.txt
Name : Parth Todankar 
GDSC-RAIT
=> Program to print hollow inverted half pyramid

Beginner-level/DSA/Check Palindrome.txt
=> Program to Check Palindrome

Beginner-level/DSA/GCD.txt
=> Program to find GCD

Beginner-level/DSA/Fibonacci.txt
=> Program for Fibonacci

Intermediate-Level/DSA/Arrange a list of integers in ascending order.txt
Program to arrange a list of integers in ascending order using Quick Sort.
GDSC-RAIT
=> Ascending order using Quick Sort

Intermediate-Level/DSA/Stack operations.txt
=> Stack-Operations

Beginner-level/DSA/Half Pyramid.txt
=> Program for Half Pyramid

Beginner-level/DSA/Print your name.txt
=> Program to print your name

Beginner-level/DSA/square of number.txt
=> Program to find square of number

Beginner-level/DSA/Check vowel or consonant.txt
=> Program to check Vowel or Consonant using Java

Beginner-level/DSA/Print even numbers.txt
=> Print Even Number

Beginner-level/DSA/Print odd numbers.txt
=> Print Odd Numbers

Beginner-level/DSA/Palindrome pattern1.txt
=> Program to print Palindrome Pyramid in Java

Beginner-level/DSA/Hollow Full Pyramid.txt
=> Hollow Full Pyramid using Java

Beginner-level/DSA/Print even numbers.txt
=> Program print even numbers

Beginner-level/DSA/Harmonic Progression.txt
=> Program to find nth term of harmonic progression

Beginner-level/DSA/Hollow Full Pyramid.txt
=> Program for hollow full pyramid

Beginner-level/DSA/GCD.txt
=> Program To Calculate GCD

Intermediate-Level/DSA/Factorial of Number.txt
=> Factorial of a Number

Intermediate-Level/App Dev/Dice Game/Guess The Colour.txt
=> Program for Color Guessing Game

Intermediate-Level/App Dev/Dice Game/Dice Game.txt
=> Program for Dice Game

Intermediate-Level/App Dev/Musical Instrument Store System/Myuzick Store.txt
=> Program for Music Store

Beginner-level/DSA/Inverted Full Pyramid.txt
=> Program for Inverted Full Pyramid

Intermediate-Level/DSA/Tower of Hanoi.txt
=> Program for Tower of Hanoi using Java

Intermediate-Level/App Dev/Unit Converter Application/Unit Converter.txt
=> Program for Unit converter using Java

Intermediate-Level/App Dev/Color guessing game/Color Guessing Game.txt
GDSC-RAIT
Earlier the code was not merge into this file of color guessing game. Hence, trying again :)
=> Program for Color Guessing Game using Java

Beginner-level/DSA/count number of space in sentence.txt
=> Program to count number of spaces using Java

Beginner-level/DSA/Binary Number to decimal number.txt
=> Binary to Decimal Number

Beginner-level/DSA/Binary Number to decimal number.txt
=> Program For Binary Number to Decimal Number

Beginner-level/DSA/Half Pyramid.txt
=> Program to print half pyramid

Intermediate-Level/App Dev/Notes App/code.java
=> Program for Basic Notes App

Beginner-level/DSA/Geometric Progression.txt
=> Program to find nth term of geometric progression

Beginner-level/DSA/Area of triangle.txt
=> Area of Triangle using Java

Beginner-level/DSA/Reverse Digits.txt
=> Program to reverse digits in CPP

Intermediate-Level/DSA/Reversing a Stack.txt
=> reversing a stack

Beginner-level/DSA/series1.txt
=> Series 1 using Java

Beginner-level/DSA/count number of space in sentence.txt
=> Program To Count Blank Spaces

Beginner-level/DSA/Convert lower case to uppercase.txt
=> Program To Convert Uppercase To Lowercase

Beginner-level/DSA/Check whether number is prime or not.txt
=> Check Whether The Number Is Prime Or Not

Beginner-level/DSA/Print odd numbers.txt
=> printing an odd number.

Beginner-level/DSA/square of number.txt
=> print square of number USING SWIFT

Beginner-level/DSA/Reverse Digits.txt
=>  Java program to reverse a number recursively

Beginner-level/DSA/Check-whether-number-is-even-or-not.txt
=> Program to check even number.

Beginner-level/DSA/Binary Number to decimal number.txt
=> Program For Binary To Decimal

Beginner-level/DSA/Print your name.txt
=> Printing Name

Beginner-level/DSA/Print prime numbers.txt
=> Program For Printing Prime Numbers

Intermediate-Level/DSA/3.3 matrix multiplication.txt
=> 3*3 matrix multiplication using Java

Beginner-level/DSA/Geometric Progression.txt
=> Geometric Progression using Java

Beginner-level/DSA/Convert lower case to uppercase.txt
=> program to convert lowercase to uppercase

Intermediate-Level/DSA/First Occurence in array.txt
Added Java Code for First Occurence of number in an array.
=> Added Java Code

Beginner-level/DSA/Print odd numbers.txt
=> Program for printing odd numbers

Beginner-level/DSA/Print even numbers.txt
=> PROGRAM TO PRINT EVEN NUMBERS

Intermediate-Level/DSA/Find maximum in stack.txt
=> Find Maximum in a Stack

Intermediate-Level/DSA/Infix to Postfix.txt
=> Infix To Postfix

Beginner-level/DSA/Print random number.txt
=> Program For Printing Random Numbers

Beginner-level/DSA/Print prime numbers.txt
=> Program for Printing Prime Number

Intermediate-Level/DSA/Sorting array.txt
=> Sorting Arrray

Intermediate-Level/DSA/Factorial of Number.txt
=> Factorial of Number

Beginner-level/DSA/convert uppercase to lowercase.txt
=> Uppercase To Lowercase

Beginner-level/DSA/series1.txt
=> Program to find nth term of series-1 using cpp

Beginner-level/DSA/Series2.txt
=> Program to find nth term of series-2

Beginner-level/DSA/Series3.txt
=> Program to find nth term of series-3

Beginner-level/DSA/Reverse Digits.txt
Reverts Google-Developer-Student-Club-RAIT/HACKTOBERFEST#154
=> Revert " Java program to reverse a number recursively"

Beginner-level/DSA/square of number.txt
Reverts Google-Developer-Student-Club-RAIT/HACKTOBERFEST#153
=> Revert "print square of number USING SWIFT"

Beginner-level/DSA/Print odd numbers.txt
=> Program to print odd numbers

Beginner-level/DSA/Print odd numbers.txt
=> Program To Print Odd Number
